// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBli9VxvaJ_6qo-_3lj-8BiAM_DlSwq6Iw',
    appId: '1:820757059875:web:368a29e56b5db2528e1496',
    messagingSenderId: '820757059875',
    projectId: 'bus-tracking-2001',
    authDomain: 'bus-tracking-2001.firebaseapp.com',
    storageBucket: 'bus-tracking-2001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfbHEvhQpj_VGeIkavhLB71X6UIXnSfSg',
    appId: '1:820757059875:android:f5065857621705248e1496',
    messagingSenderId: '820757059875',
    projectId: 'bus-tracking-2001',
    storageBucket: 'bus-tracking-2001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAPgAhmJFfA3DaBRK0Q4QLTUZb0xq2pbg',
    appId: '1:820757059875:ios:9cb28fbbf3718ca68e1496',
    messagingSenderId: '820757059875',
    projectId: 'bus-tracking-2001',
    storageBucket: 'bus-tracking-2001.firebasestorage.app',
    iosBundleId: 'com.example.carTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAPgAhmJFfA3DaBRK0Q4QLTUZb0xq2pbg',
    appId: '1:820757059875:ios:9cb28fbbf3718ca68e1496',
    messagingSenderId: '820757059875',
    projectId: 'bus-tracking-2001',
    storageBucket: 'bus-tracking-2001.firebasestorage.app',
    iosBundleId: 'com.example.carTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBli9VxvaJ_6qo-_3lj-8BiAM_DlSwq6Iw',
    appId: '1:820757059875:web:c5d9ad6160fafa258e1496',
    messagingSenderId: '820757059875',
    projectId: 'bus-tracking-2001',
    authDomain: 'bus-tracking-2001.firebaseapp.com',
    storageBucket: 'bus-tracking-2001.firebasestorage.app',
  );
}
